#!/bin/bash
# =============================================================================
# Development Environment Setup
# =============================================================================
# Auto-generated by mle init. Checks required development tooling for this
# project's detected tech stack. Safe to re-run (idempotent).
#
# Usage:
#   bash scripts/setup-dev-environment.sh
#   bash scripts/setup-dev-environment.sh --check-only
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

CHECK_ONLY=false
[[ "${1:-}" == "--check-only" ]] && CHECK_ONLY=true

PASS=0
FAIL=0

check() {
    local name="$1"
    local cmd="$2"
    local install_hint="${3:-}"

    if eval "$cmd" &>/dev/null; then
        echo -e "  ${GREEN}[ok]${NC}      $name"
        PASS=$((PASS + 1))
    else
        echo -e "  ${RED}[fail]${NC}    $name"
        [[ -n "$install_hint" ]] && echo -e "            Fix: $install_hint"
        FAIL=$((FAIL + 1))
    fi
}

echo ""
echo -e "${BOLD}Development Environment Check${NC}"
echo ""
# Nodejs checks
check "Node.js >= 24" \
    "node -e 'process.exit(parseInt(process.version.slice(1)) >= 24 ? 0 : 1)'" \
    "Install Node.js 24+ (nvm install 24)"

check "npm" \
    "command -v npm" \
    "Installed with Node.js"

# Universal checks
check "pre-commit" \
    "command -v pre-commit" \
    "pip install pre-commit"

check "git-lfs" \
    "command -v git-lfs" \
    "sudo apt install git-lfs || brew install git-lfs"

check "Git identity" \
    "git config user.name && git config user.email" \
    "git config --global user.name 'Your Name' && git config --global user.email 'you@example.com'"
echo ""
echo -e "${BOLD}Summary:${NC} $PASS passed, $FAIL failed"
echo ""

if [[ "$CHECK_ONLY" == "false" ]]; then
    echo -e "${BOLD}Installing git hooks via lefthook...${NC}"
    (cd "$REPO_ROOT" && npx --no-install lefthook install)
fi

if [[ $FAIL -gt 0 ]]; then
    echo -e "${YELLOW}Some checks failed. Please install missing tools.${NC}"
    exit 1
fi
